const prodactCards = [
  {
    id: 1,
    title: "Kungaboqar yog'i Oila tanlovi,tozalangan va xidsizlantirilgan",
    heart: "⭐" + " 4.9 (4092 sharsh)",
    rasrochka: "19716 som/oyiga",
    realPrice: "250 000",
    skidka: "169 000 som",
    img1: "./img/kungaboqar.svg",
    isLiked: false,
  },
  {
    id: 2,
    title: "Erkaklar shimlari, klassik, tekis chinos",
    content: "4.9 (64sharhlar)",
    heart: "⭐" + " 4.9 (4092 sharsh)",
    realPrice: "250 000",
    skidka: "169 000 som",
    img1: "./img/t_product_540_high.jpg.svg",
    isLiked: false,
  },
  {
    id: 3,
    title: "Erkaklar shimlari, klassik, tekis chinos",
    content: "4.9 (64sharhlar)",
    heart: "⭐" + " 4.9 (4092 sharsh)",
    realPrice: "250 000",
    skidka: "169 000 som",
    img1: "./img/t_product_540_high.jpg (1).svg",
    isLiked: false,
  },
  {
    id: 4,
    title: "Erkaklar shimlari, klassik, tekis chinos",
    content: "4.9 (64sharhlar)",
    heart: "⭐" + " 4.9 (4092 sharsh)",
    realPrice: "250 000",
    skidka: "169 000 som",
    img1: "./img/t_product_540_high.jpg.png",
    isLiked: false,
  },
  {
    id: 5,
    title: "Kungaboqar yog'i Oila tanlovi,tozalangan va xidsizlantirilgan",
    heart: "⭐" + " 4.9 (4092 sharsh)",
    rasrochka: "19716 som/oyiga",
    realPrice: "250 000",
    skidka: "169 000 som",
    img1: "./img/t_product_540_high.jpg (1).png",
    isLiked: true,
  },
  {
    id: 6,
    title: "Kungaboqar yog'i Oila tanlovi,tozalangan va xidsizlantirilgan",
    heart: "⭐" + " 4.9 (4092 sharsh)",
    rasrochka: "19716 som/oyiga",
    realPrice: "250 000",
    skidka: "169 000 som",
    img1: "./img/t_product_540_high.jpg (2).png",
    isLiked: false,
  },
  {
    id: 7,
    title: "Kungaboqar yog'i Oila tanlovi,tozalangan va xidsizlantirilgan",
    heart: "⭐" + " 4.9 (4092 sharsh)",
    rasrochka: "19716 som/oyiga",
    realPrice: "250 000",
    skidka: "169 000 som",
    img1: "./img/t_product_540_high.jpg (3).png",
    isLiked: false,
  },
  {
    id: 8,
    title: "Kungaboqar yog'i Oila tanlovi,tozalangan va xidsizlantirilgan",
    heart: "⭐" + " 4.9 (4092 sharsh)",
    rasrochka: "19716 som/oyiga",
    realPrice: "250 000",
    skidka: "169 000 som",
    img1: "./img/t_product_540_high.jpg (4).png",
    isLiked: false,
  },
  {
    id: 9,
    title: "Kungaboqar yog'i Oila tanlovi,tozalangan va xidsizlantirilgan",
    heart: "⭐" + " 4.9 (4092 sharsh)",
    rasrochka: "19716 som/oyiga",
    realPrice: "250 000",
    skidka: "169 000 som",
    img1: "./img/t_product_540_high.jpg (5).png",
    isLiked: false,
  },
  {
    id: 10,
    title: "Kungaboqar yog'i Oila tanlovi,tozalangan va xidsizlantirilgan",
    heart: "⭐" + " 4.9 (4092 sharsh)",
    rasrochka: "19716 som/oyiga",
    realPrice: "250 000",
    skidka: "169 000 som",
    img1: "./img/t_product_540_high.jpg (6).png",
    isLiked: false,
  },
  {
    id: 11,
    title: "Erkaklar shimlari, klassik, tekis chinos",
    content: "4.9 (64sharhlar)",
    heart: "⭐" + " 4.9 (4092 sharsh)",
    realPrice: "250 000",
    skidka: "169 000 som",
    img1: "./img/t_product_540_high.jpg.svg",
    isLiked: false,
  },
];

export default prodactCards;
